name: Auto Refresh GitHub Stats

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  refresh-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Generate random number
        id: rand
        run: echo "RAND=$RANDOM" >> $GITHUB_ENV

      - name: Fetch GitHub Stats with random query
        run: |
          echo "Refreshing GitHub Stats..."
          curl -s "https://github-readme-stats.vercel.app/api?username=MayankLuthyagi&count_private=true&include_all_commits=true&cache_seconds=1&rand=$RAND&v=1"
          curl -s "https://streak-stats.demolab.com?user=MayankLuthyagi&include_all_commits=true&rand=$RAND"
